<?php
declare(strict_types=1);

/*
 * SWIR Chat API v1.1
 * PHP 8.0+ / PDO MySQL / MySQL or MariaDB.
 * Supports the Web Edition shell and the trusted Desktop Edition shell origin.
 */
const SWIR_CHAT_API_VERSION = '1.1';
const SWIR_CHAT_CONFIG = __DIR__ . '/swir-chat-config.php';
const SWIR_CHAT_WEB_ORIGIN = 'https://swir.github.io';
const SWIR_CHAT_DESKTOP_ORIGIN = 'https://swir.local';

function h(string $v): string { return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function current_api_url(): string {
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || ((int)($_SERVER['SERVER_PORT'] ?? 80) === 443);
    $scheme = $https ? 'https' : 'http';
    $host = (string)($_SERVER['HTTP_HOST'] ?? 'localhost');
    $uri = strtok((string)($_SERVER['REQUEST_URI'] ?? '/swir-chat-api.php'), '?');
    return $scheme . '://' . $host . $uri;
}
function json_out(array $data, int $status = 200): never {
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}
function random_key(int $bytes = 24): string { return bin2hex(random_bytes($bytes)); }
function valid_origin(string $origin): bool {
    return (bool)preg_match('~^https://[A-Za-z0-9.-]+(?::\d+)?$~', $origin);
}
function normalize_origins(string $raw): array {
    $items = preg_split('/[\s,]+/', trim($raw)) ?: [];
    $out = [];
    foreach ($items as $item) {
        $origin = rtrim(trim($item), '/');
        if ($origin === '') continue;
        if (!valid_origin($origin)) throw new InvalidArgumentException('Every allowed origin must be an HTTPS origin.');
        $out[$origin] = true;
    }
    if (!$out) throw new InvalidArgumentException('At least one allowed origin is required.');
    if (count($out) > 8) throw new InvalidArgumentException('A maximum of 8 allowed origins is supported.');
    return array_keys($out);
}
function configured_origins(array $cfg): array {
    $raw = $cfg['allowed_origins'] ?? null;
    if (is_array($raw)) {
        $origins = [];
        foreach ($raw as $item) {
            $origin = rtrim(trim((string)$item), '/');
            if ($origin !== '' && valid_origin($origin)) $origins[$origin] = true;
        }
    } else {
        $legacy = rtrim(trim((string)($cfg['allowed_origin'] ?? '')), '/');
        $origins = $legacy !== '' && valid_origin($legacy) ? [$legacy => true] : [];
        if ($legacy === SWIR_CHAT_WEB_ORIGIN) $origins[SWIR_CHAT_DESKTOP_ORIGIN] = true;
    }
    return array_keys($origins);
}
function config_php(array $cfg): string {
    return "<?php\n// Generated by SWIR Chat installer. Do not publish this file as text.\nreturn " . var_export($cfg, true) . ";\n";
}

if (!is_file(SWIR_CHAT_CONFIG)) {
    $error = '';
    $installed = null;
    if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['install'] ?? '') === '1') {
        $dbHost = trim((string)($_POST['db_host'] ?? 'localhost'));
        $dbPort = max(1, min(65535, (int)($_POST['db_port'] ?? 3306)));
        $dbName = trim((string)($_POST['db_name'] ?? ''));
        $dbUser = trim((string)($_POST['db_user'] ?? ''));
        $dbPass = (string)($_POST['db_pass'] ?? '');
        $rawOrigins = (string)($_POST['allowed_origins'] ?? (SWIR_CHAT_WEB_ORIGIN . ', ' . SWIR_CHAT_DESKTOP_ORIGIN));
        $roomName = trim((string)($_POST['room_name'] ?? 'SWIR GENERAL'));
        try { $origins = normalize_origins($rawOrigins); }
        catch (Throwable $e) { $origins = []; $error = $e->getMessage(); }

        if ($error === '' && ($dbHost === '' || $dbName === '' || $dbUser === '')) $error = 'Database host, database name and database user are required.';
        elseif ($error === '' && ($roomName === '' || mb_strlen($roomName) > 64)) $error = 'Room name must be between 1 and 64 characters.';
        elseif ($error === '' && !is_writable(__DIR__)) $error = 'This directory is not writable. PHP must be able to create swir-chat-config.php.';

        if ($error === '') {
            try {
                $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
                $pdo = new PDO($dsn, $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false]);
                $pdo->exec("CREATE TABLE IF NOT EXISTS swir_chat_messages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,room VARCHAR(64) NOT NULL DEFAULT 'general',client_id VARCHAR(80) NOT NULL,nickname VARCHAR(32) NOT NULL,message VARCHAR(500) NOT NULL,ip_hash CHAR(64) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (id),INDEX idx_room_id (room, id),INDEX idx_client_created (client_id, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
                $pdo->exec("CREATE TABLE IF NOT EXISTS swir_chat_presence (client_id VARCHAR(80) NOT NULL,room VARCHAR(64) NOT NULL DEFAULT 'general',nickname VARCHAR(32) NOT NULL,last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (client_id),INDEX idx_room_seen (room, last_seen)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
                $cfg = ['db_host'=>$dbHost,'db_port'=>$dbPort,'db_name'=>$dbName,'db_user'=>$dbUser,'db_pass'=>$dbPass,'allowed_origins'=>$origins,'room_name'=>$roomName,'public_key'=>random_key(24),'admin_key'=>random_key(32),'created_at'=>gmdate('c')];
                if (@file_put_contents(SWIR_CHAT_CONFIG, config_php($cfg), LOCK_EX) === false) throw new RuntimeException('Could not write swir-chat-config.php. Check folder permissions.');
                @chmod(SWIR_CHAT_CONFIG, 0640);
                $installed = $cfg;
            } catch (Throwable $e) { $error = $e->getMessage(); }
        }
    }
    $apiUrl = current_api_url();
    ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SWIR Chat Server Installer</title><style>:root{color-scheme:dark;--a:#35e6ff;--l:rgba(53,230,255,.23);--m:#86a7b9;--ok:#50e3a4;--bad:#ff718c}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#0b2940,transparent 34%),linear-gradient(145deg,#020812,#071522 55%,#020a13);color:#edfaff;font-family:Inter,Segoe UI,Arial,sans-serif;padding:24px}.wrap{width:min(780px,100%);margin:auto;border:1px solid var(--l);border-radius:24px;padding:24px;background:#071525e8}.k{font:800 11px Consolas,monospace;letter-spacing:.16em;color:var(--a)}h1{font-size:clamp(34px,7vw,64px);margin:8px 0}.lead,.small{color:var(--m);line-height:1.6}.lead{font-size:13px}.small{font-size:10px}.field{margin:11px 0}.field label{display:block;color:#86a9bb;font:800 9px Consolas,monospace;letter-spacing:.11em;margin-bottom:6px}.input{width:100%;padding:11px 12px;border:1px solid var(--l);border-radius:11px;background:#03101d;color:white}.grid{display:grid;grid-template-columns:1fr 130px;gap:10px}.btn{width:100%;margin-top:12px;padding:12px;border:1px solid #35e6ff77;border-radius:12px;background:#00a6ff22;color:white;cursor:pointer}.error,.success{padding:12px;border:1px solid var(--l);border-radius:12px}.error{color:#ff9aab;border-color:#ff718c66}.success{color:var(--ok)}.value{padding:10px;border:1px solid var(--l);border-radius:10px;background:#03101d;color:#dff9ff;overflow-wrap:anywhere;margin:5px 0 13px}@media(max-width:620px){body{padding:10px}.wrap{padding:16px}.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap"><div class="k">SWIR CHAT // SERVER INSTALLER 1.1</div><h1>Database setup</h1><p class="lead">Creates the SWIR Chat tables, API keys and a strict CORS allowlist for Web Edition and Desktop Edition.</p>
    <?php if ($installed): ?><section class="success"><h2>INSTALLATION COMPLETE</h2><p class="small">Keep the Admin Key private.</p><strong>API URL</strong><div class="value"><?=h($apiUrl)?></div><strong>PUBLIC CHAT KEY</strong><div class="value"><?=h($installed['public_key'])?></div><strong>ADMIN KEY</strong><div class="value"><?=h($installed['admin_key'])?></div><p class="small">Allowed origins: <?=h(implode(', ', $installed['allowed_origins']))?><br>Room: <?=h($installed['room_name'])?></p></section>
    <?php else: ?><?php if ($error): ?><div class="error"><?=h($error)?></div><?php endif; ?><form method="post" autocomplete="off"><input type="hidden" name="install" value="1"><div class="grid"><div class="field"><label>DATABASE HOST</label><input class="input" name="db_host" value="<?=h((string)($_POST['db_host'] ?? 'localhost'))?>" required></div><div class="field"><label>PORT</label><input class="input" name="db_port" type="number" value="<?=h((string)($_POST['db_port'] ?? '3306'))?>" required></div></div><div class="field"><label>DATABASE NAME</label><input class="input" name="db_name" required></div><div class="field"><label>DATABASE USER</label><input class="input" name="db_user" required></div><div class="field"><label>DATABASE PASSWORD</label><input class="input" name="db_pass" type="password"></div><div class="field"><label>ALLOWED HTTPS ORIGINS (comma separated)</label><input class="input" name="allowed_origins" value="<?=h((string)($_POST['allowed_origins'] ?? (SWIR_CHAT_WEB_ORIGIN . ', ' . SWIR_CHAT_DESKTOP_ORIGIN)))?>" required></div><div class="field"><label>ROOM NAME</label><input class="input" name="room_name" maxlength="64" value="<?=h((string)($_POST['room_name'] ?? 'SWIR GENERAL'))?>" required></div><button class="btn" type="submit">INSTALL DATABASE + GENERATE API KEYS</button></form><?php endif; ?>
    </main></body></html><?php exit;
}

$cfg = require SWIR_CHAT_CONFIG;
if (!is_array($cfg)) json_out(['ok'=>false,'error'=>'Invalid server config'], 500);
$allowedOrigins = configured_origins($cfg);
$requestOrigin = rtrim((string)($_SERVER['HTTP_ORIGIN'] ?? ''), '/');
$originAllowed = $requestOrigin === '' || in_array($requestOrigin, $allowedOrigins, true);
if ($requestOrigin !== '' && $originAllowed) {
    header('Access-Control-Allow-Origin: ' . $requestOrigin);
    header('Vary: Origin');
    header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, X-SWIR-Key');
    header('Access-Control-Max-Age: 86400');
}
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code($originAllowed ? 204 : 403); exit; }
if (!$originAllowed) json_out(['ok'=>false,'error'=>'Origin not allowed'], 403);

function api_key(): string { return trim((string)($_SERVER['HTTP_X_SWIR_KEY'] ?? '')); }
if (!isset($cfg['public_key']) || !hash_equals((string)$cfg['public_key'], api_key())) json_out(['ok'=>false,'error'=>'Invalid Public Chat Key'], 401);
try {
    $dsn = 'mysql:host=' . $cfg['db_host'] . ';port=' . (int)$cfg['db_port'] . ';dbname=' . $cfg['db_name'] . ';charset=utf8mb4';
    $pdo = new PDO($dsn, (string)$cfg['db_user'], (string)$cfg['db_pass'], [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
} catch (Throwable) { json_out(['ok'=>false,'error'=>'Database unavailable'], 503); }
function body_json(): array { $raw=file_get_contents('php://input'); if($raw===false||$raw==='')return[]; $v=json_decode($raw,true); return is_array($v)?$v:[]; }
function clean_client(string $v): string { $v=trim($v); return preg_match('/^[A-Za-z0-9._:-]{6,80}$/',$v)?$v:''; }
function clean_nick(string $v): string { $v=trim(preg_replace('/\s+/u',' ',$v)??''); return mb_strlen($v)>=2&&mb_strlen($v)<=24?$v:''; }
function clean_room(string $v): string { return 'general'; }
function client_ip_hash(): ?string { $ip=(string)($_SERVER['REMOTE_ADDR']??''); return $ip===''?null:hash('sha256',$ip); }
function normalize_message_row(array $row): array { return ['id'=>(int)$row['id'],'room'=>(string)$row['room'],'client_id'=>(string)$row['client_id'],'nickname'=>(string)$row['nickname'],'message'=>(string)$row['message'],'created_at'=>gmdate('c',strtotime((string)$row['created_at'])?:time())]; }
$action = strtolower(trim((string)($_GET['action'] ?? 'status')));
if ($action==='status' && $_SERVER['REQUEST_METHOD']==='GET') {
    $pdo->exec("DELETE FROM swir_chat_presence WHERE last_seen < (NOW() - INTERVAL 45 SECOND)");
    $count=(int)$pdo->query("SELECT COUNT(*) FROM swir_chat_presence WHERE room='general'")->fetchColumn();
    json_out(['ok'=>true,'name'=>'SWIR Chat','api_version'=>SWIR_CHAT_API_VERSION,'room'=>'general','room_name'=>(string)($cfg['room_name']??'SWIR GENERAL'),'online'=>$count,'max_message'=>500,'poll_interval'=>1500,'server_time'=>gmdate('c')]);
}
if ($action==='messages' && $_SERVER['REQUEST_METHOD']==='GET') {
    $after=max(0,(int)($_GET['after']??0)); $limit=max(1,min(100,(int)($_GET['limit']??60)));
    if($after>0){$st=$pdo->prepare("SELECT id,room,client_id,nickname,message,created_at FROM swir_chat_messages WHERE room='general' AND id>? ORDER BY id ASC LIMIT {$limit}");$st->execute([$after]);}
    else{$st=$pdo->query("SELECT * FROM (SELECT id,room,client_id,nickname,message,created_at FROM swir_chat_messages WHERE room='general' ORDER BY id DESC LIMIT {$limit}) recent ORDER BY id ASC");}
    json_out(['ok'=>true,'messages'=>array_map('normalize_message_row',$st->fetchAll()),'poll_interval'=>1500]);
}
if ($action==='presence' && $_SERVER['REQUEST_METHOD']==='POST') {
    $b=body_json();$client=clean_client((string)($b['client_id']??''));$nick=clean_nick((string)($b['nickname']??''));$room=clean_room((string)($b['room']??'general'));
    if($client===''||$nick==='')json_out(['ok'=>false,'error'=>'Invalid client or nickname'],422);
    $st=$pdo->prepare("INSERT INTO swir_chat_presence (client_id,room,nickname,last_seen) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE room=VALUES(room),nickname=VALUES(nickname),last_seen=NOW()");$st->execute([$client,$room,$nick]);
    $pdo->exec("DELETE FROM swir_chat_presence WHERE last_seen < (NOW() - INTERVAL 45 SECOND)");
    $st=$pdo->prepare("SELECT client_id,nickname,last_seen FROM swir_chat_presence WHERE room=? ORDER BY nickname ASC LIMIT 100");$st->execute([$room]);
    $users=array_map(static fn(array $u):array=>['client_id'=>(string)$u['client_id'],'nickname'=>(string)$u['nickname'],'last_seen'=>gmdate('c',strtotime((string)$u['last_seen'])?:time())],$st->fetchAll());
    json_out(['ok'=>true,'users'=>$users]);
}
if ($action==='send' && $_SERVER['REQUEST_METHOD']==='POST') {
    $b=body_json();$client=clean_client((string)($b['client_id']??''));$nick=clean_nick((string)($b['nickname']??''));$room=clean_room((string)($b['room']??'general'));$message=trim((string)($b['message']??''));
    if($client===''||$nick==='')json_out(['ok'=>false,'error'=>'Invalid client or nickname'],422);
    if($message===''||mb_strlen($message)>500)json_out(['ok'=>false,'error'=>'Message must contain 1–500 characters'],422);
    $rate=$pdo->prepare("SELECT COUNT(*) FROM swir_chat_messages WHERE client_id=? AND created_at > (NOW() - INTERVAL 1 SECOND)");$rate->execute([$client]);if((int)$rate->fetchColumn()>0)json_out(['ok'=>false,'error'=>'Slow down a little'],429);
    $st=$pdo->prepare("INSERT INTO swir_chat_messages (room,client_id,nickname,message,ip_hash) VALUES (?,?,?,?,?)");$st->execute([$room,$client,$nick,$message,client_ip_hash()]);$id=(int)$pdo->lastInsertId();
    $st=$pdo->prepare("SELECT id,room,client_id,nickname,message,created_at FROM swir_chat_messages WHERE id=?");$st->execute([$id]);$row=$st->fetch();
    $presence=$pdo->prepare("INSERT INTO swir_chat_presence (client_id,room,nickname,last_seen) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE room=VALUES(room),nickname=VALUES(nickname),last_seen=NOW()");$presence->execute([$client,$room,$nick]);
    json_out(['ok'=>true,'message'=>normalize_message_row($row)]);
}
json_out(['ok'=>false,'error'=>'Unknown endpoint or method'],404);
