<?php
declare(strict_types=1);

/*
 * SWIR Chat API v1
 * Upload this file to PHP 8.0+ hosting with MySQL/MariaDB.
 * First visit opens the installer. The installer creates the tables and
 * writes swir-chat-config.php next to this file.
 */

const SWIR_CHAT_API_VERSION = 1;
const SWIR_CHAT_CONFIG = __DIR__ . '/swir-chat-config.php';

function h(string $v): string { return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function current_api_url(): string {
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || ((int)($_SERVER['SERVER_PORT'] ?? 80) === 443);
    $scheme = $https ? 'https' : 'http';
    $host = (string)($_SERVER['HTTP_HOST'] ?? 'localhost');
    $uri = strtok((string)($_SERVER['REQUEST_URI'] ?? '/swir-chat-api.php'), '?');
    return $scheme . '://' . $host . $uri;
}
function json_out(array $data, int $status = 200): never {
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}
function random_key(int $bytes = 24): string { return bin2hex(random_bytes($bytes)); }
function valid_origin(string $origin): bool {
    return (bool)preg_match('~^https?://[A-Za-z0-9.-]+(?::\d+)?$~', $origin);
}
function config_php(array $cfg): string {
    return "<?php\n// Generated by SWIR Chat installer. Do not publish this file as text.\nreturn " . var_export($cfg, true) . ";\n";
}

/* -------------------- Installer -------------------- */
if (!is_file(SWIR_CHAT_CONFIG)) {
    $error = '';
    $installed = null;

    if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['install'] ?? '') === '1') {
        $dbHost = trim((string)($_POST['db_host'] ?? 'localhost'));
        $dbPort = max(1, min(65535, (int)($_POST['db_port'] ?? 3306)));
        $dbName = trim((string)($_POST['db_name'] ?? ''));
        $dbUser = trim((string)($_POST['db_user'] ?? ''));
        $dbPass = (string)($_POST['db_pass'] ?? '');
        $origin = rtrim(trim((string)($_POST['allowed_origin'] ?? 'https://swir.github.io')), '/');
        $roomName = trim((string)($_POST['room_name'] ?? 'SWIR GENERAL'));

        if ($dbHost === '' || $dbName === '' || $dbUser === '') {
            $error = 'Database host, database name and database user are required.';
        } elseif (!valid_origin($origin)) {
            $error = 'Allowed Origin must look like https://swir.github.io';
        } elseif ($roomName === '' || mb_strlen($roomName) > 64) {
            $error = 'Room name must be between 1 and 64 characters.';
        } elseif (!is_writable(__DIR__)) {
            $error = 'This directory is not writable. PHP must be able to create swir-chat-config.php.';
        } else {
            try {
                $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
                $pdo = new PDO($dsn, $dbUser, $dbPass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES => false,
                ]);

                $pdo->exec("CREATE TABLE IF NOT EXISTS swir_chat_messages (
                    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    room VARCHAR(64) NOT NULL DEFAULT 'general',
                    client_id VARCHAR(80) NOT NULL,
                    nickname VARCHAR(32) NOT NULL,
                    message VARCHAR(500) NOT NULL,
                    ip_hash CHAR(64) NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    INDEX idx_room_id (room, id),
                    INDEX idx_client_created (client_id, created_at)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

                $pdo->exec("CREATE TABLE IF NOT EXISTS swir_chat_presence (
                    client_id VARCHAR(80) NOT NULL,
                    room VARCHAR(64) NOT NULL DEFAULT 'general',
                    nickname VARCHAR(32) NOT NULL,
                    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (client_id),
                    INDEX idx_room_seen (room, last_seen)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

                $cfg = [
                    'db_host' => $dbHost,
                    'db_port' => $dbPort,
                    'db_name' => $dbName,
                    'db_user' => $dbUser,
                    'db_pass' => $dbPass,
                    'allowed_origin' => $origin,
                    'room_name' => $roomName,
                    'public_key' => random_key(24),
                    'admin_key' => random_key(32),
                    'created_at' => gmdate('c'),
                ];

                $written = @file_put_contents(SWIR_CHAT_CONFIG, config_php($cfg), LOCK_EX);
                if ($written === false) {
                    throw new RuntimeException('Could not write swir-chat-config.php. Check folder permissions.');
                }
                @chmod(SWIR_CHAT_CONFIG, 0640);
                $installed = $cfg;
            } catch (Throwable $e) {
                $error = $e->getMessage();
            }
        }
    }

    $apiUrl = current_api_url();
    ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SWIR Chat Server Installer</title><style>
    :root{color-scheme:dark;--a:#35e6ff;--l:rgba(53,230,255,.23);--m:#86a7b9;--ok:#50e3a4;--bad:#ff718c}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#0b2940,transparent 34%),linear-gradient(145deg,#020812,#071522 55%,#020a13);color:#edfaff;font-family:Inter,Segoe UI,Arial,sans-serif;padding:24px}.wrap{width:min(780px,100%);margin:auto;border:1px solid var(--l);border-radius:24px;padding:24px;background:#071525e8;box-shadow:0 30px 90px #0007}.k{font:800 11px Consolas,monospace;letter-spacing:.16em;color:var(--a)}h1{font-size:clamp(34px,7vw,64px);letter-spacing:-.045em;margin:8px 0}.lead{color:var(--m);font-size:13px;line-height:1.65}.note{padding:12px;border:1px solid var(--l);border-radius:13px;background:#ffffff05;color:#a9c7d7;font:11px/1.6 Consolas,monospace;margin:16px 0}.grid{display:grid;grid-template-columns:1fr 130px;gap:10px}.field{margin:11px 0}.field label{display:block;color:#86a9bb;font:800 9px Consolas,monospace;letter-spacing:.11em;margin-bottom:6px}.input{width:100%;padding:11px 12px;border:1px solid var(--l);border-radius:11px;background:#03101d;color:white;outline:none}.input:focus{border-color:#35e6ff88}.btn{width:100%;margin-top:12px;padding:12px;border:1px solid #35e6ff77;border-radius:12px;background:#00a6ff22;color:white;cursor:pointer;font:900 10px Consolas,monospace}.error{padding:11px;border:1px solid #ff718c66;border-radius:12px;color:#ff9aab;background:#ff718c0c;font:11px/1.5 Consolas,monospace}.success{padding:18px;border:1px solid #50e3a455;border-radius:17px;background:#50e3a408}.success h2{color:var(--ok);margin-top:0}.value{padding:10px;border:1px solid var(--l);border-radius:10px;background:#03101d;color:#dff9ff;overflow-wrap:anywhere;font:11px/1.5 Consolas,monospace;margin:5px 0 13px}.warn{color:#ffca72}.small{font-size:10px;color:#7597a9;line-height:1.55}@media(max-width:620px){body{padding:10px}.wrap{padding:16px}.grid{grid-template-columns:1fr}}
    </style></head><body><main class="wrap"><div class="k">SWIR CHAT // SERVER INSTALLER</div><h1>Database setup</h1><p class="lead">Create an empty MySQL/MariaDB database in your hosting panel first. This installer connects to it, creates the SWIR Chat tables and generates a Public Chat Key plus a separate private Admin Key.</p>
    <?php if ($installed): ?>
      <section class="success"><h2>INSTALLATION COMPLETE</h2><p class="small">Paste only the API URL and Public Chat Key into SWIR Chat. Keep the Admin Key private — it is reserved for the future moderation console.</p><strong class="small">API URL</strong><div class="value"><?=h($apiUrl)?></div><strong class="small">PUBLIC CHAT KEY</strong><div class="value"><?=h($installed['public_key'])?></div><strong class="small warn">ADMIN KEY — SAVE THIS SOMEWHERE SAFE</strong><div class="value"><?=h($installed['admin_key'])?></div><p class="small">Allowed browser origin: <?=h($installed['allowed_origin'])?><br>Room: <?=h($installed['room_name'])?><br><br>Refresh this page now. The installer will be disabled and the API will enter normal server mode.</p></section>
    <?php else: ?>
      <div class="note">REQUIREMENTS: PHP 8.0+ • PDO MySQL • MySQL/MariaDB • HTTPS strongly recommended.<br>GitHub Pages origin: <b>https://swir.github.io</b></div>
      <?php if ($error): ?><div class="error"><?=h($error)?></div><?php endif; ?>
      <form method="post" autocomplete="off"><input type="hidden" name="install" value="1"><div class="grid"><div class="field"><label>DATABASE HOST</label><input class="input" name="db_host" value="<?=h((string)($_POST['db_host'] ?? 'localhost'))?>" required></div><div class="field"><label>PORT</label><input class="input" name="db_port" type="number" value="<?=h((string)($_POST['db_port'] ?? '3306'))?>" required></div></div><div class="field"><label>DATABASE NAME</label><input class="input" name="db_name" value="<?=h((string)($_POST['db_name'] ?? ''))?>" required></div><div class="field"><label>DATABASE USER</label><input class="input" name="db_user" value="<?=h((string)($_POST['db_user'] ?? ''))?>" required></div><div class="field"><label>DATABASE PASSWORD</label><input class="input" name="db_pass" type="password"></div><div class="field"><label>ALLOWED ORIGIN</label><input class="input" name="allowed_origin" value="<?=h((string)($_POST['allowed_origin'] ?? 'https://swir.github.io'))?>" required></div><div class="field"><label>ROOM NAME</label><input class="input" name="room_name" maxlength="64" value="<?=h((string)($_POST['room_name'] ?? 'SWIR GENERAL'))?>" required></div><button class="btn" type="submit">INSTALL DATABASE + GENERATE API KEYS</button></form>
    <?php endif; ?>
    </main></body></html><?php
    exit;
}

/* -------------------- Runtime -------------------- */
$cfg = require SWIR_CHAT_CONFIG;
if (!is_array($cfg)) json_out(['ok' => false, 'error' => 'Invalid server config'], 500);
$allowedOrigin = rtrim((string)($cfg['allowed_origin'] ?? ''), '/');
$requestOrigin = rtrim((string)($_SERVER['HTTP_ORIGIN'] ?? ''), '/');

if ($requestOrigin !== '' && hash_equals($allowedOrigin, $requestOrigin)) {
    header('Access-Control-Allow-Origin: ' . $allowedOrigin);
    header('Vary: Origin');
    header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, X-SWIR-Key');
    header('Access-Control-Max-Age: 86400');
}
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    if ($requestOrigin !== '' && !hash_equals($allowedOrigin, $requestOrigin)) http_response_code(403);
    else http_response_code(204);
    exit;
}
if ($requestOrigin !== '' && !hash_equals($allowedOrigin, $requestOrigin)) {
    json_out(['ok' => false, 'error' => 'Origin not allowed'], 403);
}

function api_key(): string { return trim((string)($_SERVER['HTTP_X_SWIR_KEY'] ?? '')); }
if (!isset($cfg['public_key']) || !hash_equals((string)$cfg['public_key'], api_key())) {
    json_out(['ok' => false, 'error' => 'Invalid Public Chat Key'], 401);
}

try {
    $dsn = 'mysql:host=' . $cfg['db_host'] . ';port=' . (int)$cfg['db_port'] . ';dbname=' . $cfg['db_name'] . ';charset=utf8mb4';
    $pdo = new PDO($dsn, (string)$cfg['db_user'], (string)$cfg['db_pass'], [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
} catch (Throwable $e) {
    json_out(['ok' => false, 'error' => 'Database unavailable'], 503);
}

function body_json(): array {
    $raw = file_get_contents('php://input');
    if ($raw === false || $raw === '') return [];
    $v = json_decode($raw, true);
    return is_array($v) ? $v : [];
}
function clean_client(string $v): string {
    $v = trim($v);
    return preg_match('/^[A-Za-z0-9._:-]{6,80}$/', $v) ? $v : '';
}
function clean_nick(string $v): string {
    $v = trim(preg_replace('/\s+/u', ' ', $v) ?? '');
    if (mb_strlen($v) < 2 || mb_strlen($v) > 24) return '';
    return $v;
}
function clean_room(string $v): string { return $v === 'general' ? 'general' : 'general'; }
function client_ip_hash(): ?string {
    $ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
    return $ip === '' ? null : hash('sha256', $ip);
}
function normalize_message_row(array $row): array {
    return [
        'id' => (int)$row['id'],
        'room' => (string)$row['room'],
        'client_id' => (string)$row['client_id'],
        'nickname' => (string)$row['nickname'],
        'message' => (string)$row['message'],
        'created_at' => gmdate('c', strtotime((string)$row['created_at']) ?: time()),
    ];
}

$action = strtolower(trim((string)($_GET['action'] ?? 'status')));

if ($action === 'status' && $_SERVER['REQUEST_METHOD'] === 'GET') {
    $pdo->exec("DELETE FROM swir_chat_presence WHERE last_seen < (NOW() - INTERVAL 45 SECOND)");
    $count = (int)$pdo->query("SELECT COUNT(*) FROM swir_chat_presence WHERE room='general'")->fetchColumn();
    json_out([
        'ok' => true,
        'name' => 'SWIR Chat',
        'api_version' => SWIR_CHAT_API_VERSION,
        'room' => 'general',
        'room_name' => (string)($cfg['room_name'] ?? 'SWIR GENERAL'),
        'online' => $count,
        'max_message' => 500,
        'poll_interval' => 1500,
        'server_time' => gmdate('c'),
    ]);
}

if ($action === 'messages' && $_SERVER['REQUEST_METHOD'] === 'GET') {
    $after = max(0, (int)($_GET['after'] ?? 0));
    $limit = max(1, min(100, (int)($_GET['limit'] ?? 60)));
    if ($after > 0) {
        $st = $pdo->prepare("SELECT id,room,client_id,nickname,message,created_at FROM swir_chat_messages WHERE room='general' AND id>? ORDER BY id ASC LIMIT {$limit}");
        $st->execute([$after]);
    } else {
        $st = $pdo->query("SELECT * FROM (SELECT id,room,client_id,nickname,message,created_at FROM swir_chat_messages WHERE room='general' ORDER BY id DESC LIMIT {$limit}) recent ORDER BY id ASC");
    }
    $messages = array_map('normalize_message_row', $st->fetchAll());
    json_out(['ok' => true, 'messages' => $messages, 'poll_interval' => 1500]);
}

if ($action === 'presence' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $b = body_json();
    $client = clean_client((string)($b['client_id'] ?? ''));
    $nick = clean_nick((string)($b['nickname'] ?? ''));
    $room = clean_room((string)($b['room'] ?? 'general'));
    if ($client === '' || $nick === '') json_out(['ok' => false, 'error' => 'Invalid client or nickname'], 422);
    $st = $pdo->prepare("INSERT INTO swir_chat_presence (client_id,room,nickname,last_seen) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE room=VALUES(room),nickname=VALUES(nickname),last_seen=NOW()");
    $st->execute([$client, $room, $nick]);
    $pdo->exec("DELETE FROM swir_chat_presence WHERE last_seen < (NOW() - INTERVAL 45 SECOND)");
    $st = $pdo->prepare("SELECT client_id,nickname,last_seen FROM swir_chat_presence WHERE room=? ORDER BY nickname ASC LIMIT 100");
    $st->execute([$room]);
    $users = array_map(static fn(array $u): array => [
        'client_id' => (string)$u['client_id'],
        'nickname' => (string)$u['nickname'],
        'last_seen' => gmdate('c', strtotime((string)$u['last_seen']) ?: time()),
    ], $st->fetchAll());
    json_out(['ok' => true, 'users' => $users]);
}

if ($action === 'send' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $b = body_json();
    $client = clean_client((string)($b['client_id'] ?? ''));
    $nick = clean_nick((string)($b['nickname'] ?? ''));
    $room = clean_room((string)($b['room'] ?? 'general'));
    $message = trim((string)($b['message'] ?? ''));
    if ($client === '' || $nick === '') json_out(['ok' => false, 'error' => 'Invalid client or nickname'], 422);
    if ($message === '' || mb_strlen($message) > 500) json_out(['ok' => false, 'error' => 'Message must contain 1–500 characters'], 422);

    $rate = $pdo->prepare("SELECT COUNT(*) FROM swir_chat_messages WHERE client_id=? AND created_at > (NOW() - INTERVAL 1 SECOND)");
    $rate->execute([$client]);
    if ((int)$rate->fetchColumn() > 0) json_out(['ok' => false, 'error' => 'Slow down a little'], 429);

    $st = $pdo->prepare("INSERT INTO swir_chat_messages (room,client_id,nickname,message,ip_hash) VALUES (?,?,?,?,?)");
    $st->execute([$room, $client, $nick, $message, client_ip_hash()]);
    $id = (int)$pdo->lastInsertId();
    $st = $pdo->prepare("SELECT id,room,client_id,nickname,message,created_at FROM swir_chat_messages WHERE id=?");
    $st->execute([$id]);
    $row = $st->fetch();

    $presence = $pdo->prepare("INSERT INTO swir_chat_presence (client_id,room,nickname,last_seen) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE room=VALUES(room),nickname=VALUES(nickname),last_seen=NOW()");
    $presence->execute([$client, $room, $nick]);
    json_out(['ok' => true, 'message' => normalize_message_row($row)]);
}

json_out(['ok' => false, 'error' => 'Unknown endpoint or method'], 404);
