<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>SWIR.Desktop.PackageTool</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="UpdateBroker.cs" />
    <Compile Include="DesktopPackageBuilder.cs" />
    <Compile Include="DesktopPackageTool.cs" />
  </ItemGroup>
</Project>
